apiVersion: apps/v1
kind: Deployment
metadata:
  name: gyo-en-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gyo-en
  template:
    metadata:
      labels:
        app: gyo-en
    spec:
      containers:
      - name: gyo-en
        image: gyo-en:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap: 
          name: gyo-en-config